package security;

public enum Permission {
    TABLE_VIEW,
    TABLE_OPERATE,
    ORDER_CREATE,
    KITCHEN_OPERATE,
    CUSTOMER_MANAGE,
    PAYMENT,
    BOOKING_MANAGE,
    INVENTORY_VIEW,
    INVENTORY_OPERATE,
    INVENTORY_APPROVE,
    MENU_MANAGE,
    CONFIG_MANAGE,
    EMPLOYEE_VIEW,
    EMPLOYEE_MANAGE,
    REPORT_VIEW,
    SHIFT_OPERATE,
    SHIFT_MANAGE,
    HOUR_PACKAGE_SELL
}
